<?php
/**
 * Copyright © 2016 Exto. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Exto\CustomerCard\Block\Adminhtml\Order\View\Info\Card */ ?>
<div data-bind="scope: 'customer-card-modal'">
    <!--ko template: getTemplate() --><!-- /ko -->
</div>
<div data-bind="scope: 'customer-card-button'">
    <button data-bind="click: open.bind($data, '<?php echo $block->getCustomerId(); ?>')">
        <span data-bind="i18n: 'Show card'"></span>
    </button>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayoutData(); ?>
        }
    }
</script>
