<?php
/**
 * Copyright © 2016 Exto. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Exto\CustomerCard\Block\Adminhtml\Customer\Card */ ?>
<div data-bind="scope: 'customer-card-modal'">
    <!--ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getProcessedJsLayout(); ?>
        }
    }
</script>
